author:
  name: This is my work
  role: Alisa Arama, Product Designer
  bio: |
    I like working across the full product lifecycle, from research to delivery and beyond. I think in systems and feel at home where user experience, design, and business converge.

    
    Talk to me about a book that impressed you, the human condition in a world consumed by information, or your latest hot take.